<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Livin' On Sweets API</Title>
    <Description>The API library for the Livin' On Sweets Rhythm Game Port from Blue Archive</Description>
    <Copyright>sanco</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AetherFramework" Version="1.1.0" />
    <PackageReference Include="ppy.osu.Framework" Version="2025.225.0" />
    <PackageReference Include="Tomlyn" Version="0.18.0" />
  </ItemGroup>

</Project>
