<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-android</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>

        <RootNamespace>LivinOnSweets.Android</RootNamespace>
        <AssemblyName>LivinOnSweets.Android</AssemblyName>
        <ApplicationId>com.sanicbtw.LivinOnSweets</ApplicationId>

        <ApplicationVersion Condition=" '$(ApplicationVersion)' == '' ">1</ApplicationVersion>
        <ApplicationDisplayVersion Condition=" '$(ApplicationDisplayVersion)' == '' ">$(Version)</ApplicationDisplayVersion>

        <!-- NullabilityInfoContextSupport is disabled by default for Android -->
        <NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>

        <!--
          Enables trim analyzers and full trimming during Release mode.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
        <TrimMode>full</TrimMode>-->
        <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <Debugger>Xamarin</Debugger>
      <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
      <AndroidKeyStore>False</AndroidKeyStore>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <Debugger>Xamarin</Debugger>
      <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
      <AndroidKeyStore>False</AndroidKeyStore>
    </PropertyGroup>
    <ItemGroup Label="Project References">
      <ProjectReference Include="..\LivinOnSweets.Game\LivinOnSweets.Game.csproj" />
      <ProjectReference Include="..\LivinOnSweets.Resources\LivinOnSweets.Resources.csproj" />
    </ItemGroup>
    <ItemGroup>
	    <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.0-preview.3.25208.1" />
      <PackageReference Include="ppy.osu.Framework.Android" Version="2025.1028.0" />
    </ItemGroup>
</Project>
