<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2025.204.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LivinOnSweets.API\LivinOnSweets.API.csproj" />
  </ItemGroup>
  
</Project>
